apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-6
  name: test-6
spec:
  containers:
  - image: nginx
    name: test-6
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
